In [85]:
import numpy as np

with open('arq.txt','r') as fp:

    linha = fp.readline()
    linha = fp.readline()
    linha = fp.readline()
    linha = fp.readline()
    linha = fp.readline()
    linha = fp.readline()

    #print(linha)
    #temperatura = float(linha[13:-3])
    #print(temperatura, type(temperatura))

    #palavras = linha.split()
    #print(palavras, type(palavras))

    #palavras = linha.split(":")
    #print(palavras, type(palavras))

    #n = linha.find(":")
    #print(n, type(n))

    #elementos = linha.split(" ")
    #print(elementos)
    #m = float(elementos[1])
    #print(m)
    #c = float(elementos[5][:-2])
    #rint(c)
    
    dimensão = linha.split()
    print(dimensão[2])
    dimensão = linha.split("x")
    numvec = int(dimensão[0][-1])
    tamvec = int(dimensão[1][0])

    lista = []
    while len(lista) < numvec*tamvec:
        linha = fp.readline()
        #lista.append(linha.split())
        lista += linha.split()
        print(lista)

    lista = np.array(lista, dtype=float)
    print(lista, type(lista), lista.dtype)

    matriz = lista.reshape((numvec, tamvec)).T
    print(matriz)


3x6
['4', '9', '8', '5', '7']
['4', '9', '8', '5', '7', '1', '2', '6', '9', '2']
['4', '9', '8', '5', '7', '1', '2', '6', '9', '2', '3', '7', '2', '1', '8']
['4', '9', '8', '5', '7', '1', '2', '6', '9', '2', '3', '7', '2', '1', '8', '2', '5', '4']
[4. 9. 8. 5. 7. 1. 2. 6. 9. 2. 3. 7. 2. 1. 8. 2. 5. 4.] <class 'numpy.ndarray'> float64
[[4. 2. 2.]
 [9. 6. 1.]
 [8. 9. 8.]
 [5. 2. 2.]
 [7. 3. 5.]
 [1. 7. 4.]]
